#!/usr/bin/env node
import { execSync } from 'child_process';
import { existsSync, statSync } from 'fs';
import { loadConfig } from './lib/config.js';

// Handle both direct calls and bin wrapper calls
const COMMAND_NAMES = ['create', 'setup', 'list', 'cleanup', 'query-config'];
const ARGV_OFFSET = COMMAND_NAMES.includes(process.argv[2]) ? 1 : 0;

const WORKTREE_PATH = process.argv[2 + ARGV_OFFSET];
const TASK_NAME = process.argv[3 + ARGV_OFFSET];

// Parse optional ai-tool and prompt
let AI_TOOL = null;
let PROMPT = '';
let config = null;

const remainingArgs = process.argv.slice(4 + ARGV_OFFSET);

// 首先加载配置以检查参数是否为有效的 AI 工具
config = loadConfig();
const availableTools = Object.keys(config.ai_tools || {});

// 检查第一个参数是否为有效的 AI 工具
if (remainingArgs.length > 0 && availableTools.includes(remainingArgs[0])) {
  AI_TOOL = remainingArgs[0];
  PROMPT = remainingArgs.slice(1).join(' ');
} else {
  PROMPT = remainingArgs.join(' ');
}

// Validation
if (!WORKTREE_PATH || !TASK_NAME || !PROMPT) {
  console.error('Usage: tmux-worktree setup <worktree-path> <task-name> [ai-tool] <prompt>');
  console.error('  If ai-tool is omitted, uses default_ai from config');
  process.exit(1);
}

try {
  execSync('command -v tmux', { stdio: 'pipe' });
} catch {
  console.error('Error: tmux not installed');
  process.exit(1);
}

if (!existsSync(WORKTREE_PATH)) {
  console.error(`Error: worktree path not found: ${WORKTREE_PATH}`);
  process.exit(1);
}
try {
  if (!statSync(WORKTREE_PATH).isDirectory()) {
    console.error(`Error: worktree path is not a directory: ${WORKTREE_PATH}`);
    process.exit(1);
  }
} catch {
  console.error(`Error: worktree path not found: ${WORKTREE_PATH}`);
  process.exit(1);
}

// 验证配置结构（loadConfig 已经确保配置存在并加载）
if (!config.ai_tools || Object.keys(config.ai_tools).length === 0) {
  console.error('Error: No AI tools defined in config');
  process.exit(1);
}

// 选择 AI 工具
if (!AI_TOOL) {
  AI_TOOL = config.default_ai || Object.keys(config.ai_tools)[0];
}

const aiConfig = config.ai_tools[AI_TOOL];
if (!aiConfig) {
  console.error(`Error: AI tool "${AI_TOOL}" not found in config`);
  console.error(`Available tools: ${Object.keys(config.ai_tools).join(', ')}`);
  process.exit(1);
}

if (!aiConfig.command) {
  console.error(`Error: AI tool "${AI_TOOL}" is missing "command" field`);
  process.exit(1);
}

// RESULT.md is now auto-generated by SessionStop hook

// 获取 session 名称
let SESSION_NAME = 'worktree-session';
if (process.env.TMUX) {
  try {
    SESSION_NAME = execSync('tmux display-message -p "#S"', { encoding: 'utf-8' }).trim();
  } catch {}
}

// 窗口名称
const WINDOW_NAME = TASK_NAME.replace(/[^a-zA-Z0-9-]/g, '-').slice(0, 20);

// 创建 session/window
try {
  execSync(`tmux new-session -d -s "${SESSION_NAME}" -n "${WINDOW_NAME}" -c "${WORKTREE_PATH}"`, { stdio: 'pipe' });
} catch {
  execSync(`tmux new-window -t "${SESSION_NAME}" -n "${WINDOW_NAME}" -c "${WORKTREE_PATH}"`, { stdio: 'pipe' });
}

// 转义并发送命令
const ESCAPED_PROMPT = PROMPT.replace(/'/g, "'\\''");
const AI_CMD = aiConfig.command.replace('{prompt}', ESCAPED_PROMPT);
execSync(`tmux send-keys -t "${SESSION_NAME}:${WINDOW_NAME}" "${AI_CMD}" C-m`, { stdio: 'pipe' });

console.log(`SESSION=${SESSION_NAME}`);
console.log(`WINDOW=${WINDOW_NAME}`);
console.log(`AI_TOOL=${AI_TOOL}`);
